server:
    port: 8082
spring:
    application:
        name: hotel-service
    datasource:
        password: root
        url: jdbc:postgresql://localhost:5432/microservices
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761//eureka
